### ISSUE TITLE
Error when post scan to injest

### ISSUE THREAD

**Issue by Schuler-Gabriel** [tiki/publish-sdk-capacitor#58]
Error when post the scan in https://ingest.mytiki.com/api/latest/microblink-receipt:

POST https://ingest.mytiki.com/api/latest/microblink-receipt 400
Error: Receipt ingestion failed: {"message":"JSON deserialization failed","detail":"Error: Error: missing field `receiptDateTime` - Cause: Error: missing field `receiptDateTime`","help":"Double-check the request body"}
    at ec.ingest (index-6e0cc0d1.js:11:1553)
    at async Xa.addReceipt (index-6e0cc0d1.js:6:372378)
    at async Xa.scan (index-6e0cc0d1.js:6:371660)

**Comment by ricardobrg** [comment]
fixed in tiki/capture-receipt-capacitor/pull/372
